/**
 * API client for the Miroir backend.
 * Uses VITE_API_URL or defaults to http://localhost:8000.
 */

const API_BASE =
  (typeof import.meta !== 'undefined' && (import.meta as { env?: { VITE_API_URL?: string } }).env?.VITE_API_URL) ||
  'http://localhost:8000'

export function apiUrl(path: string): string {
  const p = path.startsWith('/') ? path : `/${path}`
  return `${API_BASE}${p}`
}

export async function apiGet<T = unknown>(path: string): Promise<T> {
  const res = await fetch(apiUrl(path))
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`API ${res.status}: ${text || res.statusText}`)
  }
  return res.json() as Promise<T>
}

export async function apiPost<T = unknown>(path: string, body?: unknown): Promise<T> {
  const res = await fetch(apiUrl(path), {
    method: 'POST',
    headers: body ? { 'Content-Type': 'application/json' } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`API ${res.status}: ${text || res.statusText}`)
  }
  return res.json() as Promise<T>
}

export async function apiPut<T = unknown>(path: string, body: unknown): Promise<T> {
  const res = await fetch(apiUrl(path), {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const text = await res.text()
    throw new Error(`API ${res.status}: ${text || res.statusText}`)
  }
  return res.json() as Promise<T>
}

// ---------------------------------------------------------------------------
// Types — must match Supabase table columns exactly
// ---------------------------------------------------------------------------

export type Contact = {
  id: string
  name: string
  email: string
  phone?: string | null
  behavior_profile: Record<string, unknown>
  risk_score?: number | null
  trust_score?: number | null
  use_case?: string | null
  created_at?: string
  updated_at?: string
}

export type Interaction = {
  id: string
  contact_id: string
  type: string                // "call" | "email"
  summary: string | null
  transcript: string | null
  outcome: string | null
  timestamp: string           // auto-generated by Supabase
}

/**
 * Decision row from Supabase `decisions` table.
 *
 * DB columns: id, contact_id, approach_chosen, reasoning,
 * confidence_score, confidence_notes, escalate, outcome,
 * outcome_notes, created_at.
 */
export type Decision = {
  id: string
  contact_id: string
  approach_chosen: string     // action value e.g. "send_email"
  reasoning: string | null
  confidence_score: number | null
  confidence_notes: string | null
  escalate: boolean | null
  outcome: string | null
  outcome_notes: string | null
  created_at: string
}

/**
 * Shape returned by POST /decisions/evaluate/{contact_id}.
 * This is the pipeline result, NOT a DB row.
 */
export type EvaluationResult = {
  action: string
  reasoning: string | null
  confidence: number
  confidence_notes: string
  escalate: boolean
  overrode_pass1: boolean
  override_reason: string | null
  pass1_recommendation: Record<string, unknown>
  pass2_recommendation: Record<string, unknown>
}

// ---------------------------------------------------------------------------
// Guidelines types (from company_guidelines Supabase table + guidelines router)
// ---------------------------------------------------------------------------

export type Guidelines = {
  id: string | null
  preset_name: string
  agent_name: string
  agent_role: string
  context_label: string
  context_value_prefix: string
  first_message_template: string
  call_rules: string
  email_rules: string
  evaluation_rules: string
  hard_rules: Array<{ id: string; description: string; enabled: boolean }>
  general_context: string
  updated_at: string | null
}

export type ActivePreset = {
  preset_name: string
  agent_name: string
  agent_role: string
  context_label: string
}

// ---------------------------------------------------------------------------
// API helpers — matches origin/main backend endpoints exactly
// ---------------------------------------------------------------------------

// ── Contacts ──
export const fetchContacts = () => apiGet<Contact[]>('/contacts')
export const fetchContact = (id: string) => apiGet<Contact>(`/contacts/${id}`)
export const fetchInteractions = (id: string) => apiGet<Interaction[]>(`/contacts/${id}/interactions`)
export const fetchDecisions = (id: string) => apiGet<Decision[]>(`/contacts/${id}/decisions`)
export const draftEmail = (contactId: string) => apiPost<Record<string, unknown>>(`/contacts/${contactId}/draft-email`)
export const executeAction = (contactId: string, action: string, decisionId?: string, overrideReason?: string) =>
  apiPost<Record<string, unknown>>(`/contacts/${contactId}/execute-action`, {
    action,
    decision_id: decisionId ?? null,
    override_reason: overrideReason ?? null,
  })
export const postCallAnalysis = (contactId: string, transcript: string) =>
  apiPost<Record<string, unknown>>(`/contacts/${contactId}/post-call`, { transcript })

// ── Decisions ── (evaluate)
export const evaluateContact = (contactId: string) => apiPost<EvaluationResult>(`/decisions/evaluate/${contactId}`)

// ── Guidelines ──
export const fetchGuidelines = () => apiGet<Guidelines>('/guidelines')
export const updateGuidelines = (body: Partial<Guidelines>) => apiPut<Guidelines>('/guidelines', body)
export const fetchActivePreset = () => apiGet<ActivePreset>('/guidelines/active')
export const fetchPresetList = () => apiGet<{ presets: string[] }>('/guidelines/presets')
export const switchPreset = (name: string) => apiPost<{ status: string; preset: string; guidelines: Guidelines }>(`/guidelines/preset/${name}`)

// ── Decisions ── (override)
export const overrideDecision = (decisionId: string, action: string, reason: string) =>
  apiPost<{ status: string; decision_id: string }>(`/decisions/${decisionId}/override`, { action, reason })

// ── Contracts ──
export async function analyzeContract(file: File) {
  const form = new FormData()
  form.append('file', file)
  const res = await fetch(apiUrl('/contracts/analyze'), { method: 'POST', body: form })
  if (!res.ok) throw new Error(`API ${res.status}: ${await res.text()}`)
  return res.json()
}
export async function analyzeContractForContact(contactId: string, file: File) {
  const form = new FormData()
  form.append('file', file)
  const res = await fetch(apiUrl(`/contracts/analyze/${contactId}`), { method: 'POST', body: form })
  if (!res.ok) throw new Error(`API ${res.status}: ${await res.text()}`)
  return res.json()
}

// ── Vapi ──
export const startCall = (contactId: string) => apiPost<Record<string, unknown>>(`/vapi/call/${contactId}`)
export const fetchPrompt = (contactId: string) => apiGet<{ system_prompt: string; first_message: string; contact_name: string }>(`/vapi/prompt/${contactId}`)
